export enum CommandEnum {
  START = 'START',
  BACK = 'BACK',
  HOME = 'HOME',
  START_CONNECT = 'START_CONNECT',
  QUESTION = 'QUESTION',
  GET_ACCESS = 'GET_ACCESS',
  JOIN_CHAT = 'JOIN_CHAT',
  DOCUMENTATION = 'DOCUMENTATION',
  PAY_WITH_YOOMONEY = 'PAY_WITH_YOOMONEY',
  OUTLINE_APPLE = 'OUTLINE_APPLE',
  OUTLINE_ANDROID = 'OUTLINE_ANDROID',
  OUTLINE_DOWNLOADED = 'OUTLINE_DOWNLOADED'
}
