export enum CommandEnum {
  START = 'START',
  BACK = 'BACK',
  HOME = 'HOME',
  START_CONNECT = 'START_CONNECT',
  OUTLINE_APPLE = 'OUTLINE_APPLE',
  OUTLINE_ANDROID = 'OUTLINE_ANDROID',
  OUTLINE_DOWNLOADED = 'OUTLINE_DOWNLOADED',

  STATUS = 'STATUS', // Статус
  GET_CONNECT = 'GET_CONNECT', // Подключиться
  TOPUP_BALANCE = 'TOPUP_BALANCE', //Купить
  QUESTION = 'QUESTION', // Помощь,
  JOIN_CHAT = 'JOIN_CHAT',

  TARIF_1 = 'TARIF_1',
  TARIF_2 = 'TARIF_2',
  TARIF_3 = 'TARIF_3',

  IAM_PAYED = 'IAM_PAYED',
  PAY_WITH_YOOMONEY = 'PAY_WITH_YOOMONEY',
}
