export enum CommandEnum {
  START = 'START',
  BACK = 'BACK',
  HOME = 'HOME',
  OUTLINE_APPLE = 'OUTLINE_APPLE',
  OUTLINE_ANDROID = 'OUTLINE_ANDROID',
  OUTLINE_DOWNLOADED = 'OUTLINE_DOWNLOADED',

  STATUS = 'STATUS', // Статус
  CONNECT = 'CONNECT', // Подключиться
  GET_ACCESS = 'GET_ACCESS',
  PAYMENT = 'PAYMENT', //Купить
  QUESTION = 'QUESTION', // Помощь,
  JOIN_CHAT = 'JOIN_CHAT',

  MONTH_TARIFF = 'MONTH_TARIFF',
  THREEMONTH_TARIFF = 'THREEMONTH_TARIFF',
  SIXMONTH_TARIFF = 'SIXMONTH_TARIFF',
  ONEDAY_TARIFF = 'ONEDAY_TARIFF',

  CONFIRM_PAYMENT = 'CONFIRM_PAYMENT',
  PAY_WITH_YOOMONEY = 'PAY_WITH_YOOMONEY',
}
